/* ================== */
/*       REGISTER     */
/* ================== */

export const REGISTER_EMPLOYEE          = "REGISTER_EMPLOYEE"
export const REGISTER_EMPLOYEE_SUCCESS  = "REGISTER_EMPLOYEE_SUCCESS"
export const REGISTER_EMPLOYEE_FAILURE  = "REGISTER_EMPLOYEE_FAILURE"



/* ================== */
/*       LOGIN        */
/* ================== */

export const LOGIN_EMPLOYEE          = "LOGIN_EMPLOYEE"
export const LOGIN_EMPLOYEE_SUCCESS  = "LOGIN_EMPLOYEE_SUCCESS"
export const LOGIN_EMPLOYEE_FAILURE  = "LOGIN_EMPLOYEE_FAILURE"

export const FIND_BY_EMAIL          = "FIND_BY_EMAIL"
export const FIND_BY_EMAIL_SUCCESS  = "FIND_BY_EMAIL_SUCCESS"
export const FIND_BY_EMAIL_FAILURE  = "FIND_BY_EMAIL_FAILURE"


/* ================== */
/*     EMPLOYEE       */
/* ================== */
export const FIND_ALL_EMPLOYEE          = "FIND_ALL_EMPLOYEE"
export const FIND_ALL_EMPLOYEE_SUCCESS  = "FIND_ALL_EMPLOYEE_SUCCESS"
export const FIND_ALL_EMPLOYEE_FAILURE  = "FIND_ALL_EMPLOYEE_FAILURE"

export const FIND_EMPLOYEE_BY_ID          = "FIND_ EMPLOYEE_BY_ID"
export const FIND_EMPLOYEE_BY_ID_SUCCESS  = "FIND_EMPLOYEE_BY_ID_SUCCESS"
export const FIND_EMPLOYEE_BY_ID_FAILURE  = "FIND_EMPLOYEE_BY_ID_FAILURE"

export const SAVE_EMPLOYEE          = "SAVE_EMPLOYEE"
export const SAVE_EMPLOYEE_SUCCESS  = "SAVE_EMPLOYEE_SUCCESS"
export const SAVE_EMPLOYEE_FAILURE  = "SAVE_EMPLOYEE_FAILURE"

export const UPDATE_EMPLOYEE          = "UPDATE_EMPLOYEE"
export const UPDATE_EMPLOYEE_SUCCESS  = "UPDATE_EMPLOYEE_SUCCESS"
export const UPDATE_EMPLOYEE_FAILURE  = "UPDATE_EMPLOYEE_FAILURE"


export const SAVE_VERIFIED          = "SAVE_VERIFIED"
export const SAVE_VERIFIED_SUCCESS = "SAVE_VERIFIED_SUCCESS"
export const SAVE_VERIFIED_FAILURE  = "SAVE_VERIFIED_FAILURE"


export const FIND_VERIFIED_BY_ID          = "FIND_ VERIFIED_BY_ID"
export const FIND_VERIFIED_BY_ID_SUCCESS  = "FIND_VERIFIED_BY_ID_SUCCESS"
export const FIND_VERIFIED_BY_ID_FAILURE  = "FIND_VERIFIED_BY_ID_FAILURE"


export const FIND_EMPLOYEE_BY_NAME          = "FIND_ EMPLOYEE_BY_NAME"
export const FIND_EMPLOYEE_BY_NAME_SUCCESS  = "FIND_EMPLOYEE_BY_NAME_SUCCESS"
export const FIND_EMPLOYEE_BY_NAME_FAILURE  = "FIND_EMPLOYEE_BY_NAME_FAILURE"


export const FIND_EMPLOYEE_BY_STATUS          = "FIND_ EMPLOYEE_BY_STATUS"
export const FIND_EMPLOYEE_BY_STATUS_SUCCESS  = "FIND_EMPLOYEE_BY_STATUS_SUCCESS"
export const FIND_EMPLOYEE_BY_STATUS_FAILURE  = "FIND_EMPLOYEE_BY_STATUS_FAILURE"


export const FIND_EMPLOYEE_BY_TIPE          = "FIND_ EMPLOYEE_BY_TIPE"
export const FIND_EMPLOYEE_BY_TIPE_SUCCESS  = "FIND_EMPLOYEE_BY_TIPE_SUCCESS"
export const FIND_EMPLOYEE_BY_TIPE_FAILURE  = "FIND_EMPLOYEE_BY_TIPE_FAILURE"

/* ================== */
/*     GRADE      */
/* ================== */

export const FIND_ALL_GRADE          = "FIND_ALL_GRADE"
export const FIND_ALL_GRADE_SUCCESS  = "FIND_ALL_GRADE_SUCCESS"
export const FIND_ALL_GRADE_FAILURE  = "FIND_ALL_GRADE_FAILURE"

export const FIND_GRADE_BY_ID          = "FIND_ GRADE_BY_ID"
export const FIND_GRADE_BY_ID_SUCCESS  = "FIND_GRADE_BY_ID_SUCCESS"
export const FIND_GRADE_BY_ID_FAILURE  = "FIND_GRADE_BY_ID_FAILURE"

export const SAVE_GRADE          = "SAVE_GRADE"
export const SAVE_GRADE_SUCCESS  = "SAVE_GRADE_SUCCESS"
export const SAVE_GRADE_FAILURE  = "SAVE_GRADE_FAILURE"

export const UPDATE_GRADE          = "UPDATE_GRADE"
export const UPDATE_GRADE_SUCCESS  = "UPDATE_GRADE_SUCCESS"
export const UPDATE_GRADE_FAILURE  = "UPDATE_GRADE_FAILURE"

/* ================== */
/*     REIMBURSE      */
/* ================== */

export const FIND_ALL_REIMBURSE                     = "FIND_ALL_REIMBURSE"
export const FIND_ALL_REIMBURSE_SUCCESS             = "FIND_ALL_REIMBURSE_SUCCESS"
export const FIND_ALL_REIMBURSE_FAILURE             = "FIND_ALL_REIMBURSE_FAILURE"

export const FIND_REIMBURSE_BY_ID                   = "FIND_ REIMBURSE_BY_ID"
export const FIND_REIMBURSE_BY_ID_SUCCESS           = "FIND_REIMBURSE_BY_ID_SUCCESS"
export const FIND_REIMBURSE_BY_ID_FAILURE           = "FIND_REIMBURSE_BY_ID_FAILURE"

export const FIND_REIMBURSE_BY_CATEGORY             = "FIND_ REIMBURSE_BY_CATEGORY"
export const FIND_REIMBURSE_BY_CATEGORY_SUCCESS     = "FIND_REIMBURSE_BY_CATEGORY_SUCCESS"
export const FIND_REIMBURSE_BY_CATEGORY_FAILURE     = "FIND_REIMBURSE_BY_CATEGORY_FAILURE"

export const UPDATE_REIMBURSE                       = "UPDATE_REIMBURSE"
export const UPDATE_REIMBURSE_SUCCESS               = "UPDATE_REIMBURSE_SUCCESS"
export const UPDATE_REIMBURSE_FAILURE               = "UPDATE_REIMBURSE_FAILURE"

/* ================== */
/*     CATEGORY       */
/* ================== */

export const FIND_ALL_CATEGORY          = "FIND_ALL_CATEGORY"
export const FIND_ALL_CATEGORY_SUCCESS  = "FIND_ALL_CATEGORY_SUCCESS"
export const FIND_ALL_CATEGORY_FAILURE  = "FIND_ALL_CATEGORY_FAILURE"


/* ================== */
/*     Reset password */
/* ================== */

export const RESET_PASSWORD          = "RESET_PASSWORD"
export const RESET_PASSWORD_SUCCESS  = "RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_FAILURE  = "RESET_PASSWORD_FAILURE"



/* ================== */
/*    Detail Contract */
/* ================== */

export const FIND_ALL_CONTRACT         = "FIND_ALL_CONTRACT"
export const FIND_ALL_CONTRACT_SUCCESS  = "FIND_ALL_CONTRACT_SUCCESS"
export const FIND_ALL_CONTRACT_FAILURE  = "FIND_ALL_CONTRACT_FAILURE"

export const FIND_CONTRACT_BY_ID          = "FIND_CONTRACT_BY_ID"
export const FIND_CONTRACT_BY_ID_SUCCESS  = "FIND_CONTRACT_BY_ID_SUCCESS"
export const FIND_CONTRACT_BY_ID_FAILURE  = "FIND_CONTRACT_BY_ID_FAILURE"

export const SAVE_CONTRACT          = "SAVE_CONTRACT"
export const SAVE_CONTRACT_SUCCESS  = "SAVE_CONTRACT_SUCCESS"
export const SAVE_CONTRACT_FAILURE  = "SAVE_CONTRACT_FAILURE"

export const UPDATE_CONTRACT        = "UPDATE_CONTRACT"
export const UPDATE_CONTRACT_SUCCESS  = "UPDATE_CONTRACT_SUCCESS"
export const UPDATE_CONTRACT_FAILURE  = "UPDATE_CONTRACT_FAILURE"

export const FIND_CONTRACT_BY_NAME          = "FIND_ CONTRACT_BY_NAME"
export const FIND_CONTRACT_BY_NAME_SUCCESS  = "FIND_CONTRACT_BY_NAME_SUCCESS"
export const FIND_CONTRACT_BY_NAME_FAILURE  = "FIND_CONTRACT_BY_NAME_FAILURE"



//
// /* ================== */
// /*    SORT BY ALPHABET*/
// /* ================== */
//
// export const SORT_BY_ALPHABET        = "SORT_BY_ALPHABET_CONTRACT"
// export const SORT_BY_ALPHABET_SUCCESS  = "SORT_BY_ALPHABET_SUCCESS"
// export const SORT_BY_ALPHABET_FAILURE  = "SORT_BY_ALPHABET_FAILURE"



/* ================== */
/*    Dashboard        */
/* ================== */

export const FIND_ALL_COUNT         = "FIND_ALL_COUNT"
export const FIND_ALL_COUNT_SUCCESS  = "FIND_ALL_COUNT_SUCCESS"
export const FIND_ALL_COUNT_FAILURE  = "FIND_ALL_CONTRACT_FAILURE"

/* ================== */
/*   FORGOT PASSWORD  */
/* ================== */

export const FORGOT_PASSWORD          = "FORGOT_PASSWORD"
export const FORGOT_PASSWORD_SUCCESS  = "FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_FAILURE  = "FORGOT_PASSWORD_FAILURE"



/* ========================== */
/*      REIMBURSE FINANCE     */
/* ========================== */

export const FIND_ALL_REIMBURSE_FINANCE                     = "FIND_ALL_REIMBURSE_FINANCE"
export const FIND_ALL_REIMBURSE_FINANCE_SUCCESS             = "FIND_ALL_REIMBURSE_FINANCE_SUCCESS"
export const FIND_ALL_REIMBURSE_FINANCE_FAILURE             = "FIND_ALL_REIMBURSE_FINANCE_FAILURE"

export const FIND_REIMBURSE_FINANCE_BY_ID                   = "FIND_ REIMBURSE_FINANCE_BY_ID"
export const FIND_REIMBURSE_FINANCE_BY_ID_SUCCESS           = "FIND_REIMBURSE_FINANCE_BY_ID_SUCCESS"
export const FIND_REIMBURSE_FINANCE_BY_ID_FAILURE           = "FIND_REIMBURSE_FINANCE_BY_ID_FAILURE"

export const FIND_REIMBURSE_FINANCE_BY_CATEGORY             = "FIND_ REIMBURSE_FINANCE_BY_CATEGORY"
export const FIND_REIMBURSE_FINANCE_BY_CATEGORY_SUCCESS     = "FIND_REIMBURSE_FINANCE_BY_CATEGORY_SUCCESS"
export const FIND_REIMBURSE_FINANCE_BY_CATEGORY_FAILURE     = "FIND_REIMBURSE_FINANCE_BY_CATEGORY_FAILURE"

export const UPDATE_REIMBURSE_FINANCE                       = "UPDATE_REIMBURSE_FINANCE"
export const UPDATE_REIMBURSE_FINANCE_SUCCESS               = "UPDATE_REIMBURSE_FINANCE_SUCCESS"
export const UPDATE_REIMBURSE_FINANCE_FAILURE               = "UPDATE_REIMBURSE_FINANCE_FAILURE"

/* ============= */
/*      BILL     */
/* ============= */

export const UPLOAD_FILE              = "UPLOAD_FILE"
export const UPLOAD_FILE_SUCCESS      = "UPLOAD_FILE_SUCCESS"
export const UPLOAD_FILE_FAILURE      = "UPLOAD_FILE_FAILURE"

export const FIND_BILL_BY_ID          = "FIND_BILL_BY_ID"
export const FIND_BILL_BY_ID_SUCCESS  = "FIND_BILL_BY_ID_SUCCESS"
export const FIND_BILL_BY_ID_FAILURE  = "FIND_BILL_BY_ID_FAILURE"

export const UPDATE_BILL              = "UPDATE_BILL"
export const UPDATE_BILL_SUCCESS      = "UPDATE_BILL_SUCCESS"
export const UPDATE_BILL_FAILURE      = "UPDATE_BILL_FAILURE"
